### ISSUE TITLE
25/7/2023: Adding the ancestral allele rules to the pipeline - what is the input?

### ISSUE THREAD

**Issue by janaobsteter** [janaobsteter/tree_seq_pipeline#3]

**Comment by janaobsteter** [comment]
The rules for inferring the ancestral allele should run if the file is not already present.
However, if the file is present, it's path is specified in the config['ancestralAllele'], which would be somewhere in the Data directory, BUT if the file is created by the pipeline, it's placed in the Projects/AncestralAllele, which is a directory created by the pipeline (both Projects/ and AncestralAllele/ are created by the pipeline). We might not want to create this directory beforehand, but how do we the specify the input if it could be coming from two different places on the disk?

Do we want to put the final file with ancestral alleles back onto the disk, but that is not in concordance with where we put the rest of the results.

**Comment by gmafrafortuna** [comment]
Can't we say that in the config file, if ancestralAllele = None it runs the est-sfs pipeline else it mv/cp from the given path to Projects/AncestralAllele? Then we always have it starting from the same location.

**Comment by janaobsteter** [comment]
That is a good point - but what happens if this file is really big? Do we want to move it?

**Comment by gmafrafortuna** [comment]
I don’t think would be too bad a problem, it is still a two col file

**Comment by janaobsteter** [comment]
Ok - if ancestral inference is required, the config file should say `null` for `ancestralAllele.`
